on:
  push:
    branches:
    - master

name: build
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      with:
        enable-stack: true
        stack-no-global: true
    - run: stack build
    - run: stack test
